[package]
name = "touying-pres"
version = "0.1.0"
entrypoint = "theme.typ"
authors = ["Quaternijkon<https://github.com/Quaternijkon>"]
license = "MIT"
description = ""
repository = "https://github.com/Quaternijkon/touying-pres"
keywords = ["presentation", "slides", "lecture", "touying", "university"]
categories = ["presentation"]
disciplines = []
compiler = "0.13.0"
exclude = ["src"]

[template]
path = "content/example"
entrypoint = "main.typ"
thumbnail = "image.png"